In [16]:
import tensorflow as tf

In [17]:
print(tf.test.is_built_with_cuda()) 
print(tf.config.experimental.list_physical_devices())

True
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [18]:
(x_train, y_train) , (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

In [19]:
x_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [20]:
x_train.shape

(50000, 32, 32, 3)

In [21]:
x_test.shape

(10000, 32, 32, 3)

In [22]:
y_train.shape

(50000, 1)

In [23]:
y_train[:5]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [24]:
x_train_scaled = x_train / 255
x_test_scaled = x_test / 255

In [25]:
x_train_scaled[0]

array([[[0.23137255, 0.24313725, 0.24705882],
        [0.16862745, 0.18039216, 0.17647059],
        [0.19607843, 0.18823529, 0.16862745],
        ...,
        [0.61960784, 0.51764706, 0.42352941],
        [0.59607843, 0.49019608, 0.4       ],
        [0.58039216, 0.48627451, 0.40392157]],

       [[0.0627451 , 0.07843137, 0.07843137],
        [0.        , 0.        , 0.        ],
        [0.07058824, 0.03137255, 0.        ],
        ...,
        [0.48235294, 0.34509804, 0.21568627],
        [0.46666667, 0.3254902 , 0.19607843],
        [0.47843137, 0.34117647, 0.22352941]],

       [[0.09803922, 0.09411765, 0.08235294],
        [0.0627451 , 0.02745098, 0.        ],
        [0.19215686, 0.10588235, 0.03137255],
        ...,
        [0.4627451 , 0.32941176, 0.19607843],
        [0.47058824, 0.32941176, 0.19607843],
        [0.42745098, 0.28627451, 0.16470588]],

       ...,

       [[0.81568627, 0.66666667, 0.37647059],
        [0.78823529, 0.6       , 0.13333333],
        [0.77647059, 0

In [26]:
def get_model():
    model = tf.keras.Sequential()

    model.add(tf.keras.layers.Flatten(input_shape = (32,32,3)))
    model.add(tf.keras.layers.Dense(3500, activation = "relu"))
    model.add(tf.keras.layers.Dense(3000, activation = "relu"))
    model.add(tf.keras.layers.Dense(2000, activation = "relu"))
    model.add(tf.keras.layers.Dense(10,activation = "sigmoid"))

    model.compile(optimizer= "adam",metrics=["accuracy"], loss="sparse_categorical_crossentropy")

    return model

In [27]:
%%timeit -n1 -r1
with tf.device("/CPU:0"):
    cpu_model = get_model().fit(x_train_scaled,y_train)

1563/1563 [==============================] - 285s 181ms/step - loss: 1.9175 - accuracy: 0.3097
4min 56s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [30]:

with tf.device("/GPU:0"):
    gpu_model = get_model().fit(x_train_scaled,y_train)

ResourceExhaustedError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} failed to allocate memory [Op:AddV2]